version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=carnet_de_bord
      - POSTGRES_USER=cdb
      - POSTGRES_PASSWORD=test
    ports:
      - '5434:5432'
    volumes:
      - cdb-pgdata:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer:4.7
    ports:
      - '8081:8080'

volumes:
  cdb-pgdata:
